# Generated by Django 3.0.4 on 2020-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=48, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('projectBlongTo', models.CharField(max_length=48, null=True)),
                ('projectEnvir', models.CharField(max_length=48, null=True)),
                ('projectApiName', models.CharField(max_length=48, null=True)),
                ('projectApiDes', models.CharField(max_length=480, null=True)),
                ('projectApiPath', models.CharField(max_length=480, null=True)),
                ('projectApiReqWay', models.CharField(max_length=48, null=True)),
                ('projectApiPare', models.CharField(max_length=4800, null=True)),
                ('projectCreatDate', models.CharField(max_length=48, null=True)),
            ],
            options={
                'db_table': 'ApiTask',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
